<?xml version="1.0" encoding="UTF-8"?>
<!--
The MIT License (MIT)

Copyright (c) 2016-2022 Objectionary.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" id="license" version="2.0">
  <xsl:variable name="eol">
    <xsl:value-of select="'&#10;'"/>
  </xsl:variable>
  <xsl:template name="license-xe">
    <xsl:call-template name="license">
      <xsl:with-param name="prefix">COMMENT '</xsl:with-param>
      <xsl:with-param name="line">
        <xsl:text/>
      </xsl:with-param>
      <xsl:with-param name="suffix">
        <xsl:text>';</xsl:text>
        <xsl:value-of select="$eol"/>
      </xsl:with-param>
      <xsl:with-param name="break">
        <xsl:text> </xsl:text>
      </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template name="license-xml">
    <xsl:comment>
      <xsl:call-template name="license">
        <xsl:with-param name="prefix">
          <xsl:text/>
        </xsl:with-param>
        <xsl:with-param name="line">
          <xsl:text/>
        </xsl:with-param>
        <xsl:with-param name="suffix">
          <xsl:text/>
        </xsl:with-param>
      </xsl:call-template>
    </xsl:comment>
  </xsl:template>
  <xsl:template name="license-dot">
    <xsl:call-template name="license">
      <xsl:with-param name="prefix">
        <xsl:text>/*</xsl:text>
      </xsl:with-param>
      <xsl:with-param name="line">
        <xsl:text> * </xsl:text>
      </xsl:with-param>
      <xsl:with-param name="suffix">
        <xsl:text> */</xsl:text>
      </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template name="license-text">
    <xsl:call-template name="license">
      <xsl:with-param name="prefix">
        <xsl:text>######</xsl:text>
      </xsl:with-param>
      <xsl:with-param name="line">
        <xsl:text># </xsl:text>
      </xsl:with-param>
      <xsl:with-param name="suffix">
        <xsl:text>######</xsl:text>
      </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template name="license">
    <xsl:param name="prefix">
      <xsl:text>/*</xsl:text>
    </xsl:param>
    <xsl:param name="line">
      <xsl:text> * </xsl:text>
    </xsl:param>
    <xsl:param name="suffix">
      <xsl:text> */</xsl:text>
    </xsl:param>
    <xsl:param name="break">
      <xsl:value-of select="$eol"/>
    </xsl:param>
    <xsl:value-of select="$prefix"/>
    <xsl:value-of select="$break"/>
    <xsl:value-of select="$line"/>
    <xsl:text>This file was auto-generated by eolang-maven-plugin</xsl:text>
    <xsl:value-of select="$break"/>
    <xsl:value-of select="$line"/>
    <xsl:text>on </xsl:text>
    <xsl:value-of select="current-dateTime()"/>
    <xsl:text>. Do not edit it,</xsl:text>
    <xsl:value-of select="$break"/>
    <xsl:value-of select="$line"/>
    <xsl:text>your changes will be discarded on the next build.</xsl:text>
    <xsl:value-of select="$break"/>
    <xsl:value-of select="$line"/>
    <xsl:value-of select="$break"/>
    <xsl:value-of select="$line"/>
    <xsl:text>The EO sources were compiled to XMIR on</xsl:text>
    <xsl:value-of select="$break"/>
    <xsl:value-of select="$line"/>
    <xsl:value-of select="@time"/>
    <xsl:text> by the compiler v.</xsl:text>
    <xsl:value-of select="@version"/>
    <xsl:text>.</xsl:text>
    <xsl:value-of select="$break"/>
    <xsl:value-of select="$suffix"/>
    <xsl:value-of select="$break"/>
    <xsl:value-of select="$break"/>
  </xsl:template>
</xsl:stylesheet>
