<?xml version="1.0" encoding="UTF-8"?>
<!--
* SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
* SPDX-License-Identifier: MIT
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:eo="https://www.eolang.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="eo xs" id="lowered" version="2.0">
  <!--
  Here every formation that the "lower" goal folded (see #8137) becomes a
  Java atom class, rendered into its own "class" element appended to the
  "object", which "JavaFiles" then writes to disk like any other. The goal
  already rewrote the formation itself: its body is gone, a "λ" marker
  stands in its place, and the "lowered" attribute names the sidecar file
  holding the body of the "lambda()" method, which is spliced in verbatim
  through "unparsed-text()" from the directory the "sidecars" parameter
  names (a "file:" URI, answered from the disk by the resolver that
  "StLowered" installs). The skeleton around the body - package, the "@XmirObject"
  annotation, the constructor with one "AtVoid" per void - is rendered here
  through the functions of "_java-names.xsl", the same ones "to-java.xsl"
  uses for the call site, so the declaration and the reference never
  diverge. A document with no lowered formations passes through unchanged.
  A lowered formation without its sidecar stops the build: the stamp and
  the sidecar are written together by the goal, so one without the other
  is an invariant violation, not an input to tolerate.
  -->
  <xsl:import href="/org/eolang/parser/_funcs.xsl"/>
  <xsl:import href="/org/eolang/maven/transpile/_java-names.xsl"/>
  <xsl:param name="disclaimer" select="'This file was auto-generated by eo-maven-plugin, your changes will be discarded on the next build'"/>
  <xsl:param name="sidecars" as="xs:string" select="''"/>
  <xsl:output encoding="UTF-8" method="xml"/>
  <!--
  The directory with the sidecar bodies, as a URI with a trailing slash.
  Empty when no directory was named, and then any lowered formation stops
  the build below.
  -->
  <xsl:variable name="eo:atoms" as="xs:string" select="if ($sidecars = '' or ends-with($sidecars, '/')) then $sidecars else concat($sidecars, '/')"/>
  <!--
  A top-level formation cannot be lowered: "classes.xsl" has already turned
  it into a class of its own, whose Java the "λ" marker suppresses, so a
  "lowered" stamp on it means the goal broke its own selection rules.
  -->
  <xsl:template match="class[@lowered]">
    <xsl:message terminate="yes">
      <xsl:text>The top-level formation '</xsl:text>
      <xsl:value-of select="@name"/>
      <xsl:text>' is marked as lowered, which the lower goal must never do</xsl:text>
    </xsl:message>
  </xsl:template>
  <xsl:template match="object">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
      <xsl:apply-templates select=".//o[@lowered]" mode="lowered"/>
    </xsl:copy>
  </xsl:template>
  <xsl:template match="o" mode="lowered">
    <xsl:if test="ancestor::nested">
      <xsl:message terminate="yes">
        <xsl:text>The formation at </xsl:text>
        <xsl:value-of select="@loc"/>
        <xsl:text> is lowered inside an anonymous one, which the lower goal must never do</xsl:text>
      </xsl:message>
    </xsl:if>
    <!--
    The digest is the only piece of the sidecar URI that comes from the
    document, so anything but the twelve hex digits the schema promises
    (a path, say) stops the build before it reaches the disk.
    -->
    <xsl:if test="not(matches(@lowered, '^[0-9a-f]{12}$'))">
      <xsl:message terminate="yes">
        <xsl:text>The formation at </xsl:text>
        <xsl:value-of select="@loc"/>
        <xsl:text> is marked as lowered with '</xsl:text>
        <xsl:value-of select="@lowered"/>
        <xsl:text>', which is not a digest of twelve hex digits</xsl:text>
      </xsl:message>
    </xsl:if>
    <xsl:variable name="file" as="xs:string" select="concat($eo:atoms, @lowered, '.java')"/>
    <xsl:if test="$eo:atoms = '' or not(unparsed-text-available($file, 'UTF-8'))">
      <xsl:message terminate="yes">
        <xsl:text>The formation at </xsl:text>
        <xsl:value-of select="@loc"/>
        <xsl:text> is marked as lowered, but its sidecar '</xsl:text>
        <xsl:value-of select="$file"/>
        <xsl:text>' is absent</xsl:text>
      </xsl:message>
    </xsl:if>
    <!--
    The chain of names from the top-level class down to this formation,
    joined with "$", exactly the way the atom template of "to-java.xsl"
    builds the name it writes after "new" at the call site.
    -->
    <xsl:variable name="class" as="xs:string" select="string-join((eo:class-name(ancestor::class[1]/@name), for $a in ancestor::abstract return eo:class-name(eo:attr-name($a/@name, false())), eo:class-name(eo:attr-name(@name, false()))), '$')"/>
    <xsl:variable name="pkg" select="/object/metas/meta[head='package'][1]/part[1]"/>
    <xsl:variable name="voids" as="xs:string*" select="for $v in o[@base = $eo:empty] return concat('new Attr(&quot;', eo:literal(eo:attr-name($v/@name, false())), '&quot;, new AtVoid(&quot;', eo:literal(eo:attr-name($v/@name, false())), '&quot;))')"/>
    <xsl:variable name="header" as="xs:string*" select="(concat('/* ', $disclaimer, ' */'), '', concat('package org.eolang', if ($pkg) then concat('.', eo:package-name($pkg)) else '', ';'), '', 'import org.eolang.*;', '')"/>
    <xsl:variable name="ctor" as="xs:string*" select="('    /**', '     * Ctor.', '     */', concat('    public ', $class, '() {'), concat('        super(new Attrs(', string-join(('new Attr(Phi.RHO, new AtRho())', $voids), ', '), '));'), '    }')"/>
    <xsl:variable name="lambda" as="xs:string*" select="('    @Override', '    public Phi lambda() {', replace(unparsed-text($file, 'UTF-8'), '[&#13;&#10;]+$', ''), '    }')"/>
    <class lowered="true">
      <xsl:attribute name="java-name">
        <xsl:text>org.eolang.</xsl:text>
        <xsl:if test="$pkg">
          <xsl:value-of select="eo:package-name($pkg)"/>
          <xsl:text>.</xsl:text>
        </xsl:if>
        <xsl:value-of select="$class"/>
      </xsl:attribute>
      <java>
        <xsl:value-of select="string-join(($header, concat('@XmirObject(oname = &quot;', eo:literal(@original-name), '&quot;)'), concat('public final class ', $class, ' extends PhDefault implements Atom {'), $ctor, '', $lambda, '}', ''), $eo:new-line)"/>
      </java>
    </class>
  </xsl:template>
  <xsl:template match="node()|@*">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>
</xsl:stylesheet>
