# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
core:
  - changed-files:
      - any-glob-to-any-file:
          - 'eo-parser/src/main/resources/XMIR.xsd'
          - 'eo-parser/**/*.g4'
          - '**/*.md'
          - '**/pom.xml'
          - '.github/**'
