# The MIT License (MIT)
#
# Copyright (c) 2016-2024 Objectionary.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# @todo #1326:30min Enable only necessary tests. Several checks
#  are not available for the project. For example a lot of
#  package name contains capital letter and such names are conventional.
---
exclude_paths:
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOdir$EOmade$EOmkdir.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOdir$EOtmpfile$EOtouch.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOdir$EOwalk.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOdeleted$EOdelete.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOexists.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOis_directory.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOmoved$EOmove.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/package-info.java"
  - "eo-runtime/src/test/java/EOorg/EOeolang/EOfs/package-info.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOopen$EOfile_stream$EOwrite$EOwritten_bytes.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOopen$EOfile_stream$EOread$EOread_bytes.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOopen$EOprocess_file.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOresolved$EOresolve.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOsize.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOtouched$EOtouch.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/Files.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOsys/EOgetenv.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOsys/EOos$EOname.java"
  - "eo-runtime/src/test/java/EOorg/EOeolang/EOfs/FilesTest.java"
  - "eo-runtime/src/test/java/EOorg/EOeolang/EOfs/EOfileTest.java"
