# @todo #1326:30min Enable only necessary tests. Several checks
#  are not available for the project. For example a lot of
#  package name contains capital letter and such names are conventional.
exclude_paths: