# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT

# See https://oss-review-toolkit.org/ort/docs/configuration/ort-yml
---
# yamllint disable rule:line-length
license_choices:
  package_license_choices:
    - package_id: "Maven:org.glassfish:javax.json:1.1.4"
      license_choices:
        - given: CDDL-1.1 OR GPL-2.0-only
          choice: CDDL-1.1
    - package_id: "Maven:javax.json:javax.json-api:1.1.4"
      license_choices:
        - given: CDDL-1.1 OR GPL-2.0-only
          choice: CDDL-1.1
excludes:
  scopes:
    - pattern: "provided.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages provided"
    - pattern: "test.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only"
