assets:
  settings.xml: cqfn/secrets#settings.xml
  pubring.gpg: cqfn/secrets#pubring.gpg
  secring.gpg: cqfn/secrets#secring.gpg
install: |
  javac -version
  pdd --file=/dev/null
merge:
  script: |
    mvn clean install -Pqulice --errors -Dstyle.color=never
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    mvn clean install -Dinvoker.skip
    mvn clean deploy -Pcqfn -Psonatype --errors --settings ../settings.xml -Dstyle.color=never

    mkdir /tmp/objectionary
    cp -R eo-runtime/src/main/eo /tmp/objectionary/objects
    cp -R eo-runtime/src/test/eo /tmp/objectionary/tests
    cp eo-parser/src/main/resources/XMIR.xsd /tmp
    branch=$(git rev-parse --abbrev-ref HEAD)
    git checkout gh-pages
    git reset --hard
    sudo /bin/bash -c "cd '$(pwd)'; git clean -fd"
    cp /tmp/XMIR.xsd .
    sed -i "s|SNAPSHOT|${tag}|" XMIR.xsd
    git add XMIR.xsd
    git commit -am "XMIR XSD ${tag}"
    rm -rf objectionary
    cp -R /tmp/objectionary .
    find objectionary -name '*.eo' | xargs sed -i "s/0\.0\.0/${tag}/g"
    git add objectionary
    find objectionary -name '*.eo' > objectionary.lst
    git add objectionary.lst
    git commit -am "objectionary ${tag}"
    git checkout "${branch}"
