# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
architect:
  - yegor256
ec2:
  type: t2.2xlarge
docker:
  image: yegor256/java
assets:
  settings.xml: yegor256/objectionary-secrets#settings.xml
  pubring.gpg: yegor256/objectionary-secrets#pubring.gpg
  secring.gpg: yegor256/objectionary-secrets#secring.gpg
install: |
  pdd --file=/dev/null
merge:
  script: |
    mvn clean install -DskipTests -Pqulice --errors -Dstyle.color=never
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1

    mvn flatten:flatten
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    sed -i "s/npm install -g eolang@[0-9]\+\.[0-9]\+\.[0-9]\+/npm install -g eolang@${tag}/g" README.md
    git commit -am "${tag}"
    mvn clean install -DskipTests -Dinvoker.skip
    mvn clean deploy -DskipTests -Pobjectionary -Psonatype --errors --settings ../settings.xml -Dstyle.color=never
