architect:
  - yegor256
docker:
  image: yegor256/rultor-image:1.13.0
assets:
  settings.xml: yegor256/objectionary-secrets#settings.xml
  pubring.gpg: yegor256/objectionary-secrets#pubring.gpg
  secring.gpg: yegor256/objectionary-secrets#secring.gpg
install: |
  sudo apt-get install -y python3-pygments
  sudo pip3 install pygments
  javac -version
  pdd --file=/dev/null
merge:
  script: |
    mvn clean install -Pqulice --errors -Dstyle.color=never
    cd paper; latexmk -pdf
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1

    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    mvn clean install -Dinvoker.skip
    mvn clean deploy -Pobjectionary -Psonatype --errors --settings ../settings.xml -Dstyle.color=never

    mkdir /tmp/objectionary
    cp -R eo-runtime/src/main/eo /tmp/objectionary/objects
    cp -R eo-runtime/src/test/eo /tmp/objectionary/tests
    cp eo-parser/src/main/resources/XMIR.xsd /tmp
    branch=$(git rev-parse --abbrev-ref HEAD)
    git checkout gh-pages
    git reset --hard
    sudo git config --global --add safe.directory "$(pwd)"
    sudo /bin/bash -c "cd '$(pwd)'; git clean -fd"
    cp /tmp/XMIR.xsd .
    sed -i "s|SNAPSHOT|${tag}|" XMIR.xsd
    git add XMIR.xsd
    git commit -am "XMIR XSD ${tag}"
    rm -rf objectionary
    cp -R /tmp/objectionary .
    find objectionary -name '*.eo' | xargs sed -i "s/0\.0\.0/${tag}/g"
    git add objectionary
    find objectionary -name '*.eo' > objectionary.lst
    git add objectionary.lst
    git commit -am "objectionary ${tag}"
    git checkout "${branch}"
