/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.parser;

import com.jcabi.matchers.XhtmlMatchers;
import org.hamcrest.MatcherAssert;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.xembly.Directives;
import org.xembly.Xembler;

/**
 * Test case for {@link LnFormation}.
 * @since 0.1
 */
@SuppressWarnings("PMD.TooManyMethods")
final class LnFormationTest {

    @Test
    void pushesFormationOntoEmptyStack() {
        final Stack stack = new Stack();
        new LnFormation(new Span("[] > foo", 1))
            .into(stack, new Globals(), new Emit());
        MatcherAssert.assertThat(
            "a top-level formation must push a BARE_FORMATION level at indent 0",
            stack.top().kind(),
            Matchers.equalTo(Kind.BARE_FORMATION)
        );
    }

    @Test
    void marksLevelAsNamedWhenSuffixPresent() {
        final Stack stack = new Stack();
        new LnFormation(new Span("[] > foo", 1))
            .into(stack, new Globals(), new Emit());
        MatcherAssert.assertThat(
            "a formation carrying `> name` must flip the pushed level's named flag",
            stack.top().named(),
            Matchers.is(true)
        );
    }

    @Test
    void leavesNamedFlagFalseForUnnamedFormation() {
        final Stack stack = new Stack();
        new LnFormation(new Span("[]", 1)).into(stack, new Globals(), new Emit());
        MatcherAssert.assertThat(
            "a suffix-less formation cannot have its named flag set",
            stack.top().named(),
            Matchers.is(false)
        );
    }

    @Test
    void marksLevelAsAtomWhenSigSuffixPresent() {
        final Stack stack = new Stack();
        new LnFormation(new Span("[] > foo /number", 1))
            .into(stack, new Globals(), new Emit());
        MatcherAssert.assertThat(
            "a formation with `/sig` must mark its level as an atom",
            stack.top().atom(),
            Matchers.is(true)
        );
    }

    @Test
    void emitsFormationAsObjectWithName() {
        final Emit emit = new Emit();
        new LnFormation(new Span("[] > foo", 1))
            .into(new Stack(), new Globals(), emit);
        emit.close();
        MatcherAssert.assertThat(
            "a named formation must emit <o name='foo' line='1' pos='0'>",
            LnFormationTest.render(emit),
            XhtmlMatchers.hasXPath("/object/o[@name='foo' and @line='1' and @pos='0']")
        );
    }

    @Test
    void emitsVoidParamsInOrder() {
        final Emit emit = new Emit();
        new LnFormation(new Span("[a b c] > foo", 1))
            .into(new Stack(), new Globals(), emit);
        emit.close();
        MatcherAssert.assertThat(
            "void params must emit as <o base='∅'/> children in source order",
            LnFormationTest.render(emit),
            XhtmlMatchers.hasXPaths(
                "/object/o[@name='foo']/o[1][@name='a' and @base='∅']",
                "/object/o[@name='foo']/o[2][@name='b' and @base='∅']",
                "/object/o[@name='foo']/o[3][@name='c' and @base='∅']"
            )
        );
    }

    @Test
    void mapsPhiParameterToGreek() {
        final Emit emit = new Emit();
        new LnFormation(new Span("[@] > foo", 1))
            .into(new Stack(), new Globals(), emit);
        emit.close();
        MatcherAssert.assertThat(
            "a `@` parameter must emit as <o name='φ' base='∅'/> per R-3.4.2 / R-9.3",
            LnFormationTest.render(emit),
            XhtmlMatchers.hasXPath("/object/o/o[@name='φ' and @base='∅']")
        );
    }

    @Test
    void emitsAtomMarkerForSig() {
        final Emit emit = new Emit();
        new LnFormation(new Span("[a b] > foo /number", 1))
            .into(new Stack(), new Globals(), emit);
        emit.close();
        MatcherAssert.assertThat(
            "an atom must emit <o name='λ' atom='<sig>'/> after the void params",
            LnFormationTest.render(emit),
            XhtmlMatchers.hasXPath("/object/o[@name='foo']/o[@name='λ' and @atom='number']")
        );
    }

    @Test
    void emitsAutoGeneratedName() {
        final Emit emit = new Emit();
        new LnFormation(new Span("[x] >>", 4))
            .into(new Stack(), new Globals(), emit);
        emit.close();
        MatcherAssert.assertThat(
            "a `>>` suffix must emit the canonical auto-name with the cactus marker",
            LnFormationTest.render(emit),
            XhtmlMatchers.hasXPath("/object/o[starts-with(@name,'a🌵')]")
        );
    }

    @Test
    void emitsPlusPrefixedAttribute() {
        final Emit emit = new Emit();
        new LnFormation(new Span("[] +> tests-foo", 1))
            .into(new Stack(), new Globals(), emit);
        emit.close();
        MatcherAssert.assertThat(
            "a `+>` test attribute must emit @name='+<name>' per §9.4",
            LnFormationTest.render(emit),
            XhtmlMatchers.hasXPath("/object/o[@name='+tests-foo']")
        );
    }

    @Test
    void emitsPlusPlusGreaterShorthandAsPlusPrefixedAttribute() {
        final Emit emit = new Emit();
        new LnFormation(new Span("++> tests-foo", 1))
            .into(new Stack(), new Globals(), emit);
        emit.close();
        MatcherAssert.assertThat(
            "a `++> name` shorthand must emit the same <o name='+<name>'> as `[] +> name`",
            LnFormationTest.render(emit),
            XhtmlMatchers.hasXPath("/object/o[@name='+tests-foo' and not(o)]")
        );
    }

    @Test
    void pushesFormationKindForPlusPlusGreaterShorthand() {
        final Stack stack = new Stack();
        new LnFormation(new Span("++> tests-foo", 1))
            .into(stack, new Globals(), new Emit());
        MatcherAssert.assertThat(
            "a `++> name` shorthand must push the same BARE_FORMATION level as `[] +> name`",
            stack.top().kind(),
            Matchers.equalTo(Kind.BARE_FORMATION)
        );
    }

    @Test
    void rejectsPhiAsPlusPlusGreaterShorthandName() {
        Assertions.assertThrows(
            ParseError.class,
            () -> new LnFormation(new Span("++> @", 1))
                .into(new Stack(), new Globals(), new Emit()),
            "`++> @` must be rejected per R-6.3.5, exactly as `[] +> @` is"
        );
    }

    @Test
    void emitsConstMarkerAttribute() {
        final Emit emit = new Emit();
        new LnFormation(new Span("[] > foo!", 1))
            .into(new Stack(), new Globals(), emit);
        emit.close();
        MatcherAssert.assertThat(
            "a `!` const marker must attach @const='' to the formation's <o>",
            LnFormationTest.render(emit),
            XhtmlMatchers.hasXPath("/object/o[@name='foo' and @const='']")
        );
    }

    @Test
    void rejectsLeadingSpaceInsideBrackets() {
        Assertions.assertThrows(
            ParseError.class,
            () -> new LnFormation(new Span("[ a]", 1))
                .into(new Stack(), new Globals(), new Emit()),
            "a leading space inside brackets must be rejected per R-3.4.4"
        );
    }

    @Test
    void rejectsTrailingSpaceInsideBrackets() {
        Assertions.assertThrows(
            ParseError.class,
            () -> new LnFormation(new Span("[a ]", 1))
                .into(new Stack(), new Globals(), new Emit()),
            "a trailing space inside brackets must be rejected per R-3.4.4"
        );
    }

    @Test
    void rejectsDoubleSpaceBetweenParameters() {
        Assertions.assertThrows(
            ParseError.class,
            () -> new LnFormation(new Span("[a  b]", 1))
                .into(new Stack(), new Globals(), new Emit()),
            "a double space between parameters must be rejected per R-3.4.5"
        );
    }

    @Test
    void rejectsRhoAsParameter() {
        Assertions.assertThrows(
            ParseError.class,
            () -> new LnFormation(new Span("[^] > foo", 1))
                .into(new Stack(), new Globals(), new Emit()),
            "`^` is not admissible as a formation parameter name per R-3.4.3"
        );
    }

    @Test
    void replacesTopOnSameIndentSibling() {
        final Stack stack = new Stack();
        new LnFormation(new Span("[] > first", 1))
            .into(stack, new Globals(), new Emit());
        new LnFormation(new Span("[] > second", 2))
            .into(stack, new Globals(), new Emit());
        MatcherAssert.assertThat(
            "a same-indent sibling formation must replace the top, leaving depth 1",
            stack.depth(),
            Matchers.equalTo(1)
        );
    }

    @Test
    void rejectsPlusGreaterAttributeWithoutPrecedingBlankLine() {
        final Emit emit = new Emit();
        new LnFormation(new Span("[] +> tests-foo", 2))
            .into(new Stack(), new Globals(), emit);
        emit.close();
        MatcherAssert.assertThat(
            "a `+>` test attribute with no blank line above must emit an R-6.5.3 error",
            LnFormationTest.render(emit),
            XhtmlMatchers.hasXPath("/object/errors/error[@line='2']")
        );
    }

    @Test
    void acceptsPlusGreaterAttributeAfterBlankLine() {
        final Emit emit = new Emit();
        final Globals globals = new Globals();
        globals.blank();
        new LnFormation(new Span("[] +> tests-foo", 2))
            .into(new Stack(), globals, emit);
        emit.close();
        MatcherAssert.assertThat(
            "a `+>` test attribute preceded by one blank line must not emit any error",
            LnFormationTest.render(emit),
            Matchers.not(XhtmlMatchers.hasXPath("/object/errors"))
        );
    }

    @Test
    void marksFirstObjectEmittedAfterPush() {
        final Globals globals = new Globals();
        new LnFormation(new Span("[] > foo", 1))
            .into(new Stack(), globals, new Emit());
        MatcherAssert.assertThat(
            "a formation must flip firstObjectEmitted so subsequent metas can be rejected",
            globals.firstObjectEmitted(),
            Matchers.is(true)
        );
    }

    /**
     * Render the emit's directives under a fresh {@code <object/>}.
     * @param emit The emit
     * @return XMIR
     */
    private static String render(final Emit emit) {
        return new Xembler(
            new Directives().add("object").append(emit.directives())
        ).xmlQuietly();
    }
}
