sets:
- source: ../eo-runtime/src/test/eo/org/eolang/as-phi-tests.eo
  yaml: .data/yaml/as-phi-tests.yaml
  destination: .data/eo/as-phi-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/bool-tests.eo
  yaml: .data/yaml/bool-tests.yaml
  destination: .data/eo/bool-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/bytes-tests.eo
  yaml: .data/yaml/bytes-tests.yaml
  destination: .data/eo/bytes-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/cage-tests.eo
  yaml: .data/yaml/cage-tests.yaml
  destination: .data/eo/cage-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/cti-test.eo
  yaml: .data/yaml/cti-test.yaml
  destination: .data/eo/cti-test.eo
- source: ../eo-runtime/src/test/eo/org/eolang/float-tests.eo
  yaml: .data/yaml/float-tests.yaml
  destination: .data/eo/float-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/goto-tests.eo
  yaml: .data/yaml/goto-tests.yaml
  destination: .data/eo/goto-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/heap-tests.eo
  yaml: .data/yaml/heap-tests.yaml
  destination: .data/eo/heap-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/int-tests.eo
  yaml: .data/yaml/int-tests.yaml
  destination: .data/eo/int-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/memory-tests.eo
  yaml: .data/yaml/memory-tests.yaml
  destination: .data/eo/memory-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/nan-tests.eo
  yaml: .data/yaml/nan-tests.yaml
  destination: .data/eo/nan-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/negative-infinity-tests.eo
  yaml: .data/yaml/negative-infinity-tests.yaml
  destination: .data/eo/negative-infinity-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/nop-tests.eo
  yaml: .data/yaml/nop-tests.yaml
  destination: .data/eo/nop-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/positive-infinity-tests.eo
  yaml: .data/yaml/positive-infinity-tests.yaml
  destination: .data/eo/positive-infinity-tests.eo
  exclude:
  - float-equal-to-nan-and-infinites-is-false-highload
- source: ../eo-runtime/src/test/eo/org/eolang/ram-tests.eo
  yaml: .data/yaml/ram-tests.yaml
  destination: .data/eo/ram-tests.eo
  exclude:
  - slice-chain
- source: ../eo-runtime/src/test/eo/org/eolang/runtime-tests.eo
  yaml: .data/yaml/runtime-tests.yaml
  destination: .data/eo/runtime-tests.eo
  exclude:
  - constant-defends-against-side-effects
- source: ../eo-runtime/src/test/eo/org/eolang/rust-tests.eo
  yaml: .data/yaml/rust-tests.yaml
  destination: .data/eo/rust-tests.eo
  enable: false
- source: ../eo-runtime/src/test/eo/org/eolang/seq-tests.eo
  yaml: .data/yaml/seq-tests.yaml
  destination: .data/eo/seq-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/string-tests.eo
  yaml: .data/yaml/string-tests.yaml
  destination: .data/eo/string-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/switch-tests.eo
  yaml: .data/yaml/switch-tests.yaml
  destination: .data/eo/switch-tests.eo
  exclude:
  - switch-complex-case
  - switch-simple-case
  # fails on windows
  - switch-strings-case
  # fails on windows
  - switch-with-all-false-cases
  # fails on windows
  - switch-with-several-true-cases
- source: ../eo-runtime/src/test/eo/org/eolang/try-tests.eo
  yaml: .data/yaml/try-tests.yaml
  destination: .data/eo/try-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/tuple-tests.eo
  yaml: .data/yaml/tuple-tests.yaml
  destination: .data/eo/tuple-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/unit-tests.eo
  yaml: .data/yaml/unit-tests.yaml
  destination: .data/eo/unit-tests.eo
- source: ../eo-runtime/src/test/eo/org/eolang/io/stdout-tests.eo
  yaml: .data/yaml/io/stdout-tests.yaml
  destination: .data/eo/io/stdout-tests.eo
  enable: false
- source: ../eo-runtime/src/test/eo/org/eolang/io/tupled-stdout-test.eo
  yaml: .data/yaml/io/tupled-stdout-test.yaml
  destination: .data/eo/io/tupled-stdout-test.eo
  enable: false
- source: ../eo-runtime/src/test/eo/org/eolang/io/tupled-stdout.eo
  yaml: .data/yaml/io/tupled-stdout.yaml
  destination: .data/eo/io/tupled-stdout.eo
  enable: false
