/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import org.cactoos.Scalar;
import org.cactoos.Text;
import org.cactoos.scalar.ScalarOf;
import org.cactoos.scalar.Unchecked;
import org.cactoos.text.TextOf;

/**
 * This is an imitation of commit hash that is generated by compiler, not git.
 * This hash is used in build process for local sources that we are compiling
 * right now. Since there is no real commit hash for such sources, we need to
 * generate them to apply caching mechanisms properly.
 *
 * @since 0.60
 */
final class ChSource implements CommitHash {

    /**
     * Source text.
     */
    private final Scalar<String> text;

    /**
     * Constructor.
     * @param src Source path
     */
    ChSource(final Path src) {
        this(src.toFile());
    }

    /**
     * Constructor.
     * @param input Source text
     */
    ChSource(final Text input) {
        this(new ScalarOf<>(input::asString));
    }

    /**
     * Constructor.
     * @param src Source file
     */
    private ChSource(final File src) {
        this(new TextOf(src));
    }

    /**
     * Constructor.
     * @param text Source text
     */
    private ChSource(final Scalar<String> text) {
        this.text = text;
    }

    @Override
    public String value() {
        try {
            return this.hash();
        } catch (final NoSuchAlgorithmException exception) {
            throw new IllegalStateException(
                "SHA-1 algorithm is not supported",
                exception
            );
        }
    }

    /**
     * Calculate SHA-1 hash of the source text.
     * @return SHA-1 hash
     * @throws NoSuchAlgorithmException If SHA-1 is not supported
     */
    private String hash() throws NoSuchAlgorithmException {
        final MessageDigest digest = MessageDigest.getInstance("SHA-1");
        final StringBuilder res = new StringBuilder(40);
        for (final byte raw : digest.digest(
            new Unchecked<>(this.text).value().getBytes(StandardCharsets.UTF_8)
        )) {
            final String hex = Integer.toHexString(0xff & raw);
            if (hex.length() == 1) {
                res.append('0');
            }
            res.append(hex);
        }
        return res.toString();
    }
}
