package org.eolang.maven;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import org.cactoos.Scalar;
import org.cactoos.Text;
import org.cactoos.scalar.ScalarOf;
import org.cactoos.scalar.Unchecked;
import org.cactoos.text.TextOf;

/**
 * This is an imitation of commit hash that is generated by compiler, not git.
 * This hash is used in build process for local sources that we are compiling
 * right now. Since there is no real commit hash for such sources, we need to
 * generate them to apply caching mechanisms properly.
 *
 * @since 0.60
 */
public final class ChSource implements CommitHash {

    private final Scalar<String> text;

    public ChSource(final Path src) {
        this(src.toFile());
    }

    public ChSource(final File src) {
        this(new TextOf(src));
    }

    private ChSource(final Text input) {
        this(new ScalarOf<>(input::asString));
    }

    ChSource(final Scalar<String> text) {
        this.text = text;
    }

    @Override
    public String value() {
        try {
            return this.hash();
        } catch (final NoSuchAlgorithmException exception) {
            throw new RuntimeException(exception);
        }
    }

    private String hash() throws NoSuchAlgorithmException {
        final MessageDigest digest = MessageDigest.getInstance("SHA-1");
        final var content = new Unchecked<String>(this.text).value();
        final StringBuilder res = new StringBuilder(0);
        for (byte raw : digest.digest(content.getBytes(StandardCharsets.UTF_8))) {
            final String hex = Integer.toHexString(0xff & raw);
            if (hex.length() == 1) {
                res.append('0');
            }
            res.append(hex);
        }
        return res.toString();
    }
}
