/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import com.jcabi.log.Logger;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;

/**
 * Transpile.
 * <p>
 *     This Maven Mojo transpiles XMIR files into Java source files.
 *     The goal of this class is to automate the process of transforming EO
 *     intermediate representations (XMIRs) into Java code, optimize the output,
 *     and integrate the results into the Maven build lifecycle for further
 *     processing.
 * </p>
 * <p>
 *     This is one of the final goals that transpiles XMIRs to Java files generated by
 *     {@link MjAssemble}, {@link MjParse} or {@link MjPull} goals.
 *     The resulting Java files are stored in the {@link Transpiling#DIR} directory.
 *     The intermediate optimized XMIRs are stored in the {@link Transpiling#PRE} directory.
 * </p>
 * @since 0.1
 */
@Mojo(
    name = "transpile",
    defaultPhase = LifecyclePhase.PROCESS_SOURCES,
    threadSafe = true,
    requiresDependencyResolution = ResolutionScope.COMPILE
)
public final class MjTranspile extends MjSafe {

    /**
     * Add to source root.
     * @checkstyle MemberNameCheck (7 lines)
     */
    @Parameter(property = "eo.addSourcesRoot")
    @SuppressWarnings("PMD.ImmutableField")
    private boolean addSourcesRoot = true;

    /**
     * Whether to transpile tests.
     * @checkstyle MemberNameCheck (7 lines)
     */
    @Parameter(property = "eo.transpileTests")
    @SuppressWarnings("PMD.ImmutableField")
    private boolean transpileTests = true;

    /**
     * Whether to wrap every dispatched object with a location-carrying
     * {@code PhSafe}, so a panic reports its {@code .eo} source position.
     * Off by default, so a production build stays lean; turn it on (as
     * {@code eo-runtime} does for its tests) to keep precise {@code .eo}
     * locations in panics.
     * @checkstyle MemberNameCheck (7 lines)
     */
    @Parameter(property = "eo.trackLocations")
    private boolean trackLocations;

    /**
     * The file to record EO object coverage hits into. When it is
     * not set (the default), no instrumentation happens; when set,
     * every located object in the generated Java is wrapped into
     * {@code PhCoverage}, which appends a hit to this file the first
     * time the object is touched at runtime.
     * @todo #5466:60min Turn raw coverage hits into an LCOV report.
     *  Right now this parameter only produces a raw, append-only
     *  {@code loc:line:pos} file: the runtime {@code PhCoverage}
     *  decorator writes every touched location into it, but nothing
     *  consumes that file yet. Add a reporter step that merges those
     *  raw hits against the full set of instrumented locations, which
     *  the transpiler already knows because it emits every wrapper,
     *  and produces an LCOV ({@code .info}) tracefile plus the covered
     *  percentage. LCOV is chosen because Codecov and Coveralls
     *  consume it directly.
     * @todo #5466:30min Enforce a minimum EO object coverage in eo-runtime.
     *  Once the LCOV report from the puzzle above exists, set
     *  {@code coverageFile} on the {@code transpile} execution in
     *  {@code eo-runtime/pom.xml} and fail the build when the covered
     *  percentage of dataized {@code .eo} objects drops below a
     *  threshold (for example 80 percent), mirroring how the existing
     *  {@code jacoco} profile binds a {@code check} goal with per-metric
     *  thresholds.
     * @checkstyle MemberNameCheck (7 lines)
     */
    @Parameter(property = "eo.coverageFile")
    private File coverageFile;

    @Override
    public void exec() throws IOException {
        new Timed(
            new Transpiling(
                this.scopedTojos().withXmir(),
                this.targetDir.toPath(),
                this.generatedDir.toPath(),
                this.cache.toPath(),
                this.cacheEnabled,
                this.plugin.getVersion(),
                this.transpileTests,
                this.xslMeasures.toPath(),
                new Tracking(this.trackTransformationSteps, this.trackLocations),
                MjTranspile.path(this.coverageFile)
            )
        ).exec();
        if (this.addSourcesRoot) {
            this.project.addCompileSourceRoot(
                this.generatedDir.toPath().toAbsolutePath().toString()
            );
            Logger.info(
                this, "The directory added to Maven 'compile-source-root': %[file]s",
                this.generatedDir
            );
            final String gtests = this.generatedDir.toPath().getParent().resolve(
                "generated-test-sources"
            ).toAbsolutePath().toString();
            this.project.addTestCompileSourceRoot(gtests);
            Logger.info(
                this, "The directory added to Maven 'test-compile-source-root': %[file]s",
                gtests
            );
        }
    }

    /**
     * The path of the given file, or NULL when the file is not set.
     * @param file The file, possibly NULL
     * @return The path, or NULL
     */
    private static Path path(final File file) {
        final Path result;
        if (file == null) {
            result = null;
        } else {
            result = file.toPath();
        }
        return result;
    }
}
