/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import com.jcabi.log.Logger;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collection;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;

/**
 * Transpile.
 *
 * <p>This Maven Mojo transpiles XMIR files into Java source files.
 * The goal of this class is to automate the process of transforming EO
 * intermediate representations (XMIRs) into Java code, optimize the output,
 * and integrate the results into the Maven build lifecycle for further
 * processing.</p>
 *
 * <p>This is one of the final goals that transpiles XMIRs to Java files generated by
 * {@link MjAssemble}, {@link MjParse} or {@link MjPull} goals.
 * The resulting Java files are stored in the {@link Transpiling#DIR} directory.
 * The intermediate optimized XMIRs are stored in the {@link Transpiling#PRE} directory.</p>
 *
 * @since 0.1
 */
@Mojo(
    name = "transpile",
    defaultPhase = LifecyclePhase.PROCESS_SOURCES,
    threadSafe = true,
    requiresDependencyResolution = ResolutionScope.COMPILE
)
public final class MjTranspile extends MjSafe {

    /**
     * Java class name, simple or fully qualified.
     */
    private static final Pattern CLASS = Pattern.compile(
        "^[A-Za-z_$][A-Za-z0-9_$]*+(?:\\.[A-Za-z_$][A-Za-z0-9_$]*+)*+$"
    );

    /**
     * Add to source root.
     */
    @Parameter(
        alias = "addSourcesRoot",
        property = "eo.addSourcesRoot",
        defaultValue = "true"
    )
    private boolean attach;

    /**
     * Whether to transpile tests.
     */
    @Parameter(
        alias = "transpileTests",
        property = "eo.transpileTests",
        defaultValue = "true"
    )
    private boolean tests;

    /**
     * Whether to wrap every dispatched object with a location-carrying
     * {@code PhSafe}, so a panic reports its {@code .eo} source position.
     * Off by default, so a production build stays lean; turn it on (as
     * {@code eo-runtime} does for its tests) to keep precise {@code .eo}
     * locations in panics.
     */
    @Parameter(alias = "trackLocations", property = "eo.trackLocations")
    private boolean located;

    /**
     * Whether to wrap every located object in the generated Java into
     * {@code PhCoverage}, so it records a coverage hit the first time it
     * is touched at runtime. Off by default, so a production build stays
     * lean. The hits are appended to the file named by the
     * {@code eo.coverageFile} system property of the JVM that runs the
     * compiled program; when that property is absent, every hit is a
     * silent no-op. In {@code eo-runtime} the {@code coverage-file}
     * profile turns this on and forwards that property to surefire in
     * one step (see its {@code pom.xml}). The {@code coverage-report}
     * Maven goal ({@link MjCoverageReport}) turns the raw hits into an
     * LCOV tracefile, bound to the {@code verify} phase since the hits
     * only exist after tests actually run. {@code eo-runtime} pairs it
     * with {@code minCoverage} on that same goal, failing the build when
     * the covered percentage of dataized {@code .eo} objects drops below
     * a threshold, mirroring how the {@code jacoco} profile binds a
     * {@code check} goal with its own per-metric thresholds.
     */
    @Parameter(alias = "coverageTracking", property = "eo.coverageTracking")
    private boolean coverage;

    /**
     * The class that a generated class extends instead of {@code PhDefault},
     * set through {@code eo.phiDefaultClass}. A tool that needs control over
     * the objects of a program can name its own subclass of
     * {@code PhDefault} here and see every {@code add()} and {@code take()}
     * the program makes. The name is written into the generated Java
     * verbatim, so a class outside {@code org.eolang} has to be named in
     * full, since the generated files import nothing but
     * {@code org.eolang.*}.
     *
     * <p>The substitution reaches every class the generated Java declares
     * with an {@code extends} clause of its own, and every object it
     * builds with {@code new}: the context of a generated
     * {@code apply()}, an anonymous abstract object, and the argument
     * of a {@code PhApplication}. An object with a {@code @base}
     * extends {@code PhOnce} instead, and keeps doing so:
     * {@code PhOnce} is a decorator, and the object it wraps is itself
     * substituted, so nothing is lost.</p>
     *
     * <p>Since the generated Java builds objects with {@code new}, the
     * named class has to offer the same constructors {@code PhDefault}
     * does where the transpiler calls them: the one taking nothing,
     * the one taking a location {@code String}, and the one taking a
     * {@code byte[]}. A class that leaves one out fails to compile in
     * generated sources.</p>
     */
    @Parameter(
        alias = "phiDefaultClass",
        property = "eo.phiDefaultClass",
        defaultValue = "PhDefault"
    )
    private String superclass;

    /**
     * The directory with the tables that {@link MjInference} writes, read by
     * {@code purify.xsl} to find out which formations are safe to cache. The
     * default is the one {@link MjInference} saves them to, so a build that
     * runs the goals in their usual order needs to say nothing here. A build
     * that skips {@code eo:inference} leaves the directory absent, and then
     * nothing is marked.
     */
    @Parameter(
        alias = "inferenceDir",
        property = "eo.inferenceDir",
        required = true,
        defaultValue = "${project.build.directory}/eo/6-inference"
    )
    private File tables;

    /**
     * Ctor.
     */
    public MjTranspile() {
        // nothing
    }

    @Override
    public void exec() throws IOException {
        try (TjsForeign tojos = this.tojos()) {
            new Timed(
                new Transpiling(
                    tojos.standalone(),
                    this.targetDir.toPath(),
                    this.generatedDir.toPath(),
                    this.tests,
                    this.roots(),
                    new Transpilation(
                        new Tracking(this.trackSteps, this.located),
                        this.coverage,
                        this.base(),
                        this.xslMeasures.toPath(),
                        this.targetDir.toPath(),
                        this.tables.toPath(),
                        this.lowered()
                    ),
                    this.stored()
                )
            ).exec();
        }
        if (this.attach) {
            this.project.addCompileSourceRoot(
                this.generatedDir.toPath().toAbsolutePath().toString()
            );
            Logger.info(
                this, "The directory added to Maven 'compile-source-root': %[file]s",
                this.generatedDir
            );
            final String gtests = this.generatedDir.toPath().getParent().resolve(
                "generated-test-sources"
            ).toAbsolutePath().toString();
            this.project.addTestCompileSourceRoot(gtests);
            Logger.info(
                this, "The directory added to Maven 'test-compile-source-root': %[file]s",
                gtests
            );
        }
    }

    private Collection<Path> roots() {
        final Path build = this.targetDir.toPath().getParent();
        return this.project.getCompileSourceRoots().stream()
            .map(Paths::get)
            .filter(root -> !root.startsWith(build))
            .collect(Collectors.toList());
    }

    // What MjLower left in its marker file, or the empty string when it
    // skipped or was disabled: whether the XMIR of this build was folded
    // through phino changes the generated Java, so it belongs in the
    // cache key that Transpilation.version() makes.
    private String lowered() throws IOException {
        final Path marker = this.targetDir.toPath()
            .resolve(Lowering.DIR)
            .resolve(Lowering.MARKER);
        String content = "";
        if (Files.exists(marker)) {
            content = Files.readString(marker).trim();
        }
        return content;
    }

    private String base() {
        if (!MjTranspile.CLASS.matcher(this.superclass).matches()) {
            throw new IllegalArgumentException(
                String.format(
                    "The value of eo.phiDefaultClass is '%s', while a Java class name matching '%s' is expected",
                    this.superclass,
                    MjTranspile.CLASS
                )
            );
        }
        return this.superclass;
    }

    // The cache is skipped when the XMIR of every step is asked for: those
    // dumps are made by the train, and a cache hit hands back a stored
    // answer without running it (#7724). The version segment is not folded
    // in here, because it differs from one source to the next: the rows of
    // the inference tables an object is named in go into it (#7945), so
    // `Transpiling` folds it in per file.
    private GlobalCache stored() {
        final GlobalCache store;
        if (this.trackSteps) {
            store = new GlobalCache.GcFresh();
        } else {
            store = this.caching(Transpiling.CACHE);
        }
        return store;
    }
}
