/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import com.jcabi.log.Logger;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collection;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;

/**
 * Transpile.
 * <p>
 *     This Maven Mojo transpiles XMIR files into Java source files.
 *     The goal of this class is to automate the process of transforming EO
 *     intermediate representations (XMIRs) into Java code, optimize the output,
 *     and integrate the results into the Maven build lifecycle for further
 *     processing.
 * </p>
 * <p>
 *     This is one of the final goals that transpiles XMIRs to Java files generated by
 *     {@link MjAssemble}, {@link MjParse} or {@link MjPull} goals.
 *     The resulting Java files are stored in the {@link Transpiling#DIR} directory.
 *     The intermediate optimized XMIRs are stored in the {@link Transpiling#PRE} directory.
 * </p>
 * @since 0.1
 */
@Mojo(
    name = "transpile",
    defaultPhase = LifecyclePhase.PROCESS_SOURCES,
    threadSafe = true,
    requiresDependencyResolution = ResolutionScope.COMPILE
)
public final class MjTranspile extends MjSafe {

    /**
     * Java class name, simple or fully qualified.
     */
    private static final Pattern CLASS = Pattern.compile(
        "^[A-Za-z_$][A-Za-z0-9_$]*+(?:\\.[A-Za-z_$][A-Za-z0-9_$]*+)*+$"
    );

    /**
     * Add to source root.
     * @checkstyle MemberNameCheck (7 lines)
     */
    @Parameter(property = "eo.addSourcesRoot")
    @SuppressWarnings("PMD.ImmutableField")
    private boolean addSourcesRoot;

    /**
     * Whether to transpile tests.
     * @checkstyle MemberNameCheck (7 lines)
     */
    @Parameter(property = "eo.transpileTests")
    @SuppressWarnings("PMD.ImmutableField")
    private boolean transpileTests;

    /**
     * Whether to wrap every dispatched object with a location-carrying
     * {@code PhSafe}, so a panic reports its {@code .eo} source position.
     * Off by default, so a production build stays lean; turn it on (as
     * {@code eo-runtime} does for its tests) to keep precise {@code .eo}
     * locations in panics.
     * @checkstyle MemberNameCheck (7 lines)
     */
    @Parameter(property = "eo.trackLocations")
    private boolean trackLocations;

    /**
     * Whether to wrap every located object in the generated Java into
     * {@code PhCoverage}, so it records a coverage hit the first time it
     * is touched at runtime. Off by default, so a production build stays
     * lean. The hits are appended to the file named by the
     * {@code eo.coverageFile} system property of the JVM that runs the
     * compiled program; when that property is absent, every hit is a
     * silent no-op. In {@code eo-runtime} the {@code coverage-file}
     * profile turns this on and forwards that property to surefire in
     * one step (see its {@code pom.xml}).
     * @todo #5466:60min Turn raw coverage hits into an LCOV report.
     *  Right now the runtime only produces a raw, append-only
     *  {@code loc:line:pos} file: the {@code PhCoverage} decorator
     *  writes every touched location into it, but nothing consumes that
     *  file yet. Add a reporter step that merges those raw hits against
     *  the full set of instrumented locations, which the transpiler
     *  already knows because it emits every wrapper, and produces an
     *  LCOV ({@code .info}) tracefile plus the covered percentage. LCOV
     *  is chosen because Codecov and Coveralls consume it directly.
     * @todo #5466:30min Enforce a minimum EO object coverage in eo-runtime.
     *  Once the LCOV report from the puzzle above exists, set
     *  {@code coverageTracking} on the {@code transpile} execution in
     *  {@code eo-runtime/pom.xml} and fail the build when the covered
     *  percentage of dataized {@code .eo} objects drops below a
     *  threshold (for example 80 percent), mirroring how the existing
     *  {@code jacoco} profile binds a {@code check} goal with per-metric
     *  thresholds.
     * @checkstyle MemberNameCheck (7 lines)
     */
    @Parameter(property = "eo.coverageTracking")
    private boolean coverageTracking;

    /**
     * The class that a generated class extends instead of {@code PhDefault},
     * set through {@code eo.phiDefaultClass}. A tool that needs control over
     * the objects of a program can name its own subclass of
     * {@code PhDefault} here and see every {@code add()} and {@code take()}
     * the program makes. The name is written into the generated Java
     * verbatim, so a class outside {@code org.eolang} has to be named in
     * full, since the generated files import nothing but
     * {@code org.eolang.*}.
     * <p>
     *     The substitution reaches every class the generated Java declares
     *     with an {@code extends} clause of its own, and every object it
     *     builds with {@code new}: the context of a generated
     *     {@code apply()}, an anonymous abstract object, and the argument
     *     of a {@code PhApplication}. An object with a {@code @base}
     *     extends {@code PhOnce} instead, and keeps doing so:
     *     {@code PhOnce} is a decorator, and the object it wraps is itself
     *     substituted, so nothing is lost.
     * </p>
     * <p>
     *     Since the generated Java builds objects with {@code new}, the
     *     named class has to offer the same constructors {@code PhDefault}
     *     does where the transpiler calls them: the one taking nothing,
     *     the one taking a location {@code String}, and the one taking a
     *     {@code byte[]}. A class that leaves one out fails to compile in
     *     generated sources.
     * </p>
     */
    @Parameter(property = "eo.phiDefaultClass", defaultValue = "PhDefault")
    private String superclass;

    /**
     * Ctor.
     */
    public MjTranspile() {
        this.addSourcesRoot = true;
        this.transpileTests = true;
    }

    @Override
    public void exec() throws IOException {
        new Timed(
            new Transpiling(
                this.scopedTojos().withXmir(),
                this.targetDir.toPath(),
                this.generatedDir.toPath(),
                this.cache.toPath(),
                this.cacheEnabled,
                this.plugin.getVersion(),
                this.transpileTests,
                this.xslMeasures.toPath(),
                new Tracking(this.trackTransformationSteps, this.trackLocations),
                this.coverageTracking,
                this.base(),
                this.roots()
            )
        ).exec();
        if (this.addSourcesRoot) {
            this.project.addCompileSourceRoot(
                this.generatedDir.toPath().toAbsolutePath().toString()
            );
            Logger.info(
                this, "The directory added to Maven 'compile-source-root': %[file]s",
                this.generatedDir
            );
            final String gtests = this.generatedDir.toPath().getParent().resolve(
                "generated-test-sources"
            ).toAbsolutePath().toString();
            this.project.addTestCompileSourceRoot(gtests);
            Logger.info(
                this, "The directory added to Maven 'test-compile-source-root': %[file]s",
                gtests
            );
        }
    }

    /**
     * The compile source roots a human wrote, which are all of them but the
     * ones inside the build directory, since a root a previous goal generated
     * holds a {@code package-info.java} of its own and would fool the
     * transpiler into skipping the file it has to write.
     * @return The directories with hand-written Java
     */
    private Collection<Path> roots() {
        final Path build = this.targetDir.toPath().getParent();
        return this.project.getCompileSourceRoots().stream()
            .map(Paths::get)
            .filter(root -> !root.startsWith(build))
            .collect(Collectors.toList());
    }

    /**
     * The name of the class that the generated classes extend, refused right
     * here when it is not a Java class name. Returning the name instead of
     * checking it apart means a caller cannot end up with a name that was
     * never looked at, since {@code to-java.xsl} copies whatever it is given
     * into the {@code extends} clause and an unusable name would surface as
     * a compilation error in generated sources, far from the option that
     * caused it.
     * @return The name of the class to extend
     */
    private String base() {
        if (!MjTranspile.CLASS.matcher(this.superclass).matches()) {
            throw new IllegalArgumentException(
                String.format(
                    "The value of eo.phiDefaultClass is '%s', while a Java class name matching '%s' is expected",
                    this.superclass,
                    MjTranspile.CLASS
                )
            );
        }
        return this.superclass;
    }
}
