/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import java.io.IOException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;

/**
 * Goes through all .class files and deletes those that
 * were created from autogenerated sources so these binaries
 * are not got into result JAR.
 * @since 0.1
 */
@Mojo(
    name = "unspile",
    defaultPhase = LifecyclePhase.PREPARE_PACKAGE,
    threadSafe = true
)
public final class MjUnspile extends MjSafe {

    @Override
    public void exec() throws IOException {
        new Unspiling(
            this.generatedDir.toPath(),
            this.classesDir.toPath(),
            this.keepBinaries
        ).exec();
    }
}
