/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import com.jcabi.log.Logger;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collection;
import java.util.List;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Package info classes.
 * @since 0.60
 */
final class PackageInfos {

    /**
     * Pattern for replacing EO (object) or EO_ (package) prefixes in package.
     */
    private static final Pattern PACKAGE = Pattern.compile("EO_?");

    /**
     * Pattern for replacing first default org.eolang package.
     */
    private static final Pattern BASE = Pattern.compile("org.eolang.");

    /**
     * Not allowed characters in package names.
     */
    private static final Pattern NOT_ALLOWED = Pattern.compile("[^a-zA-Z0-9_.$]");

    /**
     * Pattern for package names beginning with a number.
     */
    private static final Pattern NUMBER_BEGINNING = Pattern.compile("^\\d.*");

    /**
     * Directory where create package info files.
     */
    private final Path root;

    /**
     * Directories with the Java sources a human wrote.
     */
    private final Collection<Path> sources;

    /**
     * Constructor.
     * @param root In which directory create files
     * @param sources Where the hand-written Java sources are
     */
    PackageInfos(final Path root, final Collection<Path> sources) {
        this.root = root;
        this.sources = sources;
    }

    /**
     * Create {@code package-info.java} files in all the directories under the {@link #root}.
     * @return Amount of created files
     * @throws IOException If fails to create a file
     */
    int create() throws IOException {
        final int size;
        if (Files.exists(this.root)) {
            final List<Path> dirs;
            try (Stream<Path> walk = Files.walk(this.root)) {
                dirs = walk.filter(
                    file -> Files.isDirectory(file)
                        && !file.equals(this.root)
                        && !file.equals(this.root.resolve("org"))
                        && !this.taken(file)
                    )
                    .collect(Collectors.toList());
            }
            for (final Path dir : dirs) {
                Logger.debug(
                    this,
                    "Created %s",
                    new Saved(
                        PackageInfos.content(
                            this.root.relativize(dir)
                                .toString()
                                .replace(File.separator, ".")
                        ), dir.resolve("package-info.java")
                    ).value()
                );
            }
            size = dirs.size();
        } else {
            Logger.info(
                this,
                "No generated sources found, skipping package-info.java creation"
            );
            size = 0;
        }
        return size;
    }

    /**
     * Does the package of this directory already have a hand-written
     * {@code package-info.java} in one of the {@link #sources}? Javac dies with
     * an internal error when one package has two {@code package-info.java} and
     * one of them carries an annotation, so the generated file gives way to the
     * one a human wrote.
     * @param dir The directory under the {@link #root}
     * @return TRUE if the package already has its own package-info.java
     */
    private boolean taken(final Path dir) {
        final Path pkg = this.root.relativize(dir);
        return this.sources.stream().anyMatch(
            src -> Files.exists(src.resolve(pkg).resolve("package-info.java"))
        );
    }

    private static String content(final String pkg) {
        return String.join(
            System.lineSeparator(),
            "/**",
            " * This file was auto-generated by eo-maven-plugin,",
            " * don't modify it, all changes will be lost anyway.",
            " */",
            String.format(
                "@org.eolang.XmirPackage(\"%s\")",
                PackageInfos.BASE.matcher(
                    PackageInfos.PACKAGE.matcher(pkg).replaceAll("")
                ).replaceFirst("")
            ),
            String.format("package %s;", PackageInfos.escaped(pkg))
        );
    }

    private static String escaped(final String pkg) {
        String escaped = PackageInfos.NOT_ALLOWED.matcher(pkg).replaceAll("_");
        if (PackageInfos.NUMBER_BEGINNING.matcher(escaped).matches()) {
            escaped = String.format("_%s", escaped);
        }
        return escaped;
    }
}
