/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import com.jcabi.log.Logger;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * Package info classes.
 * @since 0.60
 */
final class PackageInfos {

    /**
     * Pattern for replacing EO in package.
     */
    private static final Pattern PACKAGE = Pattern.compile("EO");

    /**
     * Not allowed characters in package names.
     */
    private static final Pattern NOT_ALLOWED = Pattern.compile("[^a-zA-Z0-9_.$]");

    /**
     * Pattern for package names beginning with a number.
     */
    private static final Pattern NUMBER_BEGINNING = Pattern.compile("^\\d.*");

    /**
     * Directory where create package info files.
     */
    private final Path root;

    /**
     * Constructor.
     * @param root In which directory create files.
     */
    PackageInfos(final Path root) {
        this.root = root;
    }

    /**
     * Create {@code package-info.java} files in all the directories under the {@link #root}.
     * @return Amount of created files
     * @throws IOException If fails to create a file
     */
    int create() throws IOException {
        final int size;
        if (Files.exists(this.root)) {
            final List<Path> dirs = Files.walk(this.root)
                .filter(file -> Files.isDirectory(file) && !file.equals(this.root))
                .collect(Collectors.toList());
            for (final Path dir : dirs) {
                Logger.debug(
                    this,
                    "Created %s",
                    new Saved(
                        PackageInfos.content(
                            this.root.relativize(dir).toString()
                                .replace(File.separator, ".")
                        ),
                        dir.resolve("package-info.java")
                    ).value()
                );
            }
            size = dirs.size();
        } else {
            Logger.info(
                this,
                "No generated sources found, skipping package-info.java creation"
            );
            size = 0;
        }
        return size;
    }

    private static String content(final String pkg) {
        return String.join(
            "\n",
            "/**",
            " * This file was auto-generated by eo-maven-plugin,",
            " * don't modify it, all changes will be lost anyway.",
            " */",
            String.format(
                "// @org.eolang.XmirPackage(\"%s\")",
                PackageInfos.PACKAGE.matcher(pkg).replaceAll("")
            ),
            String.format("package %s;", PackageInfos.escaped(pkg))
        );
    }

    private static String escaped(final String pkg) {
        String escaped = PackageInfos.NOT_ALLOWED.matcher(pkg).replaceAll("_");
        if (PackageInfos.NUMBER_BEGINNING.matcher(escaped).matches()) {
            escaped = String.format("_%s", escaped);
        }
        return escaped;
    }
}
