/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import com.github.lombrozo.xnav.Xnav;
import com.jcabi.log.Logger;
import com.jcabi.xml.XML;
import com.jcabi.xml.XMLDocument;
import java.io.IOException;
import java.nio.file.Path;
import java.util.Collection;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Function;
import java.util.function.Supplier;
import org.eolang.parser.OnDefault;
import org.eolang.parser.OnDetailed;

/**
 * Transpile.
 *
 * <p>This class transpiles XMIR files into Java source files.
 * The goal of this class is to automate the process of transforming EO
 * intermediate representations (XMIRs) into Java code, optimize the output,
 * and integrate the results into the Maven build lifecycle for further
 * processing.</p>
 *
 * <p>This is one of the final goals that transpiles XMIRs to Java files generated by
 * {@link MjAssemble}, {@link MjParse} or {@link MjPull} goals.
 * The resulting Java files are stored in the {@link #DIR} directory.
 * The intermediate optimized XMIRs are stored in the {@link #PRE} directory.</p>
 *
 * @since 0.1
 * @todo #6125:60min Take the writing of the Java files out of here too.
 *  {@link JavaFiles} still keeps a cache directory and an enabled flag of
 *  its own, so this class has to be handed one ready-made, and the key of
 *  that directory repeats the plugin version {@link GlobalCache} already
 *  folds in. Give {@link JavaFiles} the same {@link GlobalCache} instead,
 *  then it goes back to being made here, and {@link #version()}, which is
 *  read by nothing but the test, goes with it. The three that are left,
 *  the generated directory, the tests flag and the roots, describe one
 *  thing, where the output lands, and belong together in an object of
 *  their own, along with the tail of {@link #exec()} that logs it.
 */
final class Transpiling implements Step {

    /**
     * The directory where to transpile to.
     */
    static final String DIR = "5-transpile";

    /**
     * The directory where to put pre-transpile files.
     */
    static final String PRE = "5-pre-transpile";

    /**
     * Cache directory for transpiled sources.
     */
    static final String CACHE = "transpiled";

    /**
     * XMIR sources to transpile.
     */
    private final Collection<TjForeign> sources;

    /**
     * Target directory.
     */
    private final Path target;

    /**
     * Generated sources directory.
     */
    private final Path generated;

    /**
     * Whether to transpile tests.
     */
    private final boolean tests;

    /**
     * Directories with the Java sources a human wrote.
     */
    private final Collection<Path> roots;

    /**
     * The XSL train that does the transpiling.
     */
    private final Transpilation train;

    /**
     * The cache this build shares with every other build on this machine.
     */
    private final GlobalCache cache;

    /**
     * The Java files this run writes, and the stale ones it removes.
     */
    private final JavaFiles files;

    /**
     * Constructor.
     * @param srcs XMIR sources to transpile
     * @param target Target directory
     * @param generated Generated sources directory
     * @param tests Whether to transpile tests
     * @param java Directories with the Java sources a human wrote
     * @param train The XSL train that does the transpiling
     * @param store The cache shared with every build on this machine
     * @param written The Java files this run writes
     */
    Transpiling(
        final Collection<TjForeign> srcs,
        final Path target,
        final Path generated,
        final boolean tests,
        final Collection<Path> java,
        final Transpilation train,
        final GlobalCache store,
        final JavaFiles written
    ) {
        this.sources = srcs;
        this.target = target;
        this.generated = generated;
        this.tests = tests;
        this.roots = java;
        this.train = train;
        this.cache = store;
        this.files = written;
    }

    @Override
    public void exec() throws IOException {
        final int transpiled = new Threaded<>(
            this.sources,
            this::transpiled
        ).total();
        this.files.removeStale();
        Logger.info(
            this, "Transpiled %d XMIRs, created %d Java files in %[file]s",
            this.sources.size(),
            transpiled + new PackageInfos(
                this.generated, this.roots, this.files.directories()
            ).create(),
            this.generated
        );
    }

    /**
     * The cache-key version segment of this transpiling.
     * @return The version segment for {@link CachePath}
     */
    String version() {
        return this.train.version();
    }

    private int transpiled(final TjForeign tojo) throws IOException {
        final Path source = tojo.xmir();
        final XML xmir = new XMLDocument(source);
        final Path base = this.target.resolve(Transpiling.DIR);
        final String name = new OnDetailed(new OnDefault(new Xnav(xmir.inner())), source).get();
        final Path dest = new Place(name).make(base, MjAssemble.XMIR);
        final Supplier<String> hsh = new TojoHash(tojo);
        final AtomicBoolean rewrite = new AtomicBoolean(false);
        final Function<XML, XML> transform = this.train.forSource(name);
        this.cache.with(this.train.version(xmir.xpath("/object/o/@loc"))).footprint(
            base.relativize(dest),
            hsh,
            src -> {
                rewrite.compareAndSet(false, true);
                return transform.apply(xmir).toString();
            }
        ).apply(source, dest);
        return this.files.total(
            rewrite.get(), dest, hsh.get(), this.tests && !tojo.discovered()
        );
    }
}
