/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import com.github.lombrozo.xnav.Filter;
import com.github.lombrozo.xnav.Xnav;
import com.jcabi.log.Logger;
import com.jcabi.xml.XML;
import com.jcabi.xml.XMLDocument;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collection;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.stream.Collectors;
import org.eolang.parser.OnDefault;
import org.eolang.parser.OnDetailed;

/**
 * Transpile.
 * <p>
 *     This class transpiles XMIR files into Java source files.
 *     The goal of this class is to automate the process of transforming EO
 *     intermediate representations (XMIRs) into Java code, optimize the output,
 *     and integrate the results into the Maven build lifecycle for further
 *     processing.
 * </p>
 * <p>
 *     This is one of the final goals that transpiles XMIRs to Java files generated by
 *     {@link MjAssemble}, {@link MjParse} or {@link MjPull} goals.
 *     The resulting Java files are stored in the {@link #DIR} directory.
 *     The intermediate optimized XMIRs are stored in the {@link #PRE} directory.
 * </p>
 * @since 0.1
 */
final class Transpiling implements Step {

    /**
     * The directory where to transpile to.
     */
    static final String DIR = "5-transpile";

    /**
     * The directory where to put pre-transpile files.
     */
    static final String PRE = "5-pre-transpile";

    /**
     * Cache directory for transpiled sources.
     */
    private static final String CACHE = "transpiled";

    /**
     * Java extension.
     */
    private static final String JAVA = "java";

    /**
     * XMIR sources to transpile.
     */
    private final Collection<TjForeign> sources;

    /**
     * Target directory.
     * @checkstyle MemberNameCheck (5 lines)
     */
    private final Path targetDir;

    /**
     * Generated sources directory.
     * @checkstyle MemberNameCheck (5 lines)
     */
    private final Path generatedDir;

    /**
     * Base cache directory.
     * @checkstyle MemberNameCheck (5 lines)
     */
    private final Path cacheDir;

    /**
     * Whether caching is enabled.
     * @checkstyle MemberNameCheck (5 lines)
     */
    private final boolean cacheEnabled;

    /**
     * Whether to transpile tests.
     * @checkstyle MemberNameCheck (5 lines)
     */
    private final boolean transpileTests;

    /**
     * The plugin version, for the log.
     */
    private final String version;

    /**
     * The XSL train that does the transpiling.
     */
    private final Transpilation train;

    /**
     * Cache guard, see {@link ConcurrentCache} for why it is one per instance.
     */
    private final ConcurrentCache guard;

    /**
     * Constructor.
     * @param srcs XMIR sources to transpile
     * @param target Target directory
     * @param generated Generated sources directory
     * @param cache Base cache directory
     * @param enabled Whether caching is enabled
     * @param ver Plugin version string
     * @param tests Whether to transpile tests
     * @param measures Path to the file where XSL measurements are stored
     * @param diagnostics Which diagnostic artifacts to emit while transpiling
     * @param cvrg Whether located objects are wrapped into {@code PhCoverage}
     * @param base The class that a generated class extends instead of {@code PhDefault}
     * @checkstyle ParameterNumberCheck (20 lines)
     */
    @SuppressWarnings("PMD.ExcessiveParameterList")
    Transpiling(
        final Collection<TjForeign> srcs,
        final Path target,
        final Path generated,
        final Path cache,
        final boolean enabled,
        final String ver,
        final boolean tests,
        final Path measures,
        final Tracking diagnostics,
        final boolean cvrg,
        final String base
    ) {
        this.sources = srcs;
        this.targetDir = target;
        this.generatedDir = generated;
        this.cacheDir = cache;
        this.cacheEnabled = enabled;
        this.transpileTests = tests;
        this.version = ver;
        this.train = new Transpilation(ver, diagnostics, cvrg, base, measures, target);
        this.guard = new ConcurrentCache();
    }

    @Override
    public void exec() throws IOException {
        Logger.info(
            this, "Transpiled %d XMIRs, created %d Java files in %[file]s",
            this.sources.size(),
            new Threaded<>(
                this.sources,
                this::transpiled
            ).total() + new PackageInfos(this.generatedDir).create(),
            this.generatedDir
        );
    }

    /**
     * The cache-key version segment of this transpiling.
     * @return The version segment for {@link CachePath}
     */
    String version() {
        return this.train.version();
    }

    /**
     * Transpile a single tojo.
     * @param tojo Tojo that should be transpiled
     * @return Number of generated Java files
     * @throws IOException If any issues with I/O
     */
    private int transpiled(final TjForeign tojo) throws IOException {
        final Path source = tojo.xmir();
        final XML xmir = new XMLDocument(source);
        final Path base = this.targetDir.resolve(Transpiling.DIR);
        final Path target = new Place(
            new OnDetailed(new OnDefault(new Xnav(xmir.inner())), source).get()
        ).make(base, MjAssemble.XMIR);
        final Supplier<String> hsh = new TojoHash(tojo);
        final AtomicBoolean rewrite = new AtomicBoolean(false);
        final Function<XML, XML> transform = this.train.forSource(source);
        final Path cdir = this.cacheDir.resolve(Transpiling.CACHE);
        final Path tail = base.relativize(target);
        if (this.cacheEnabled) {
            this.guard.apply(
                source, target, tail,
                new Cache(
                    new CachePath(cdir, this.version(), hsh.get()),
                    src -> {
                        rewrite.compareAndSet(false, true);
                        final String res = transform.apply(xmir).toString();
                        Logger.debug(
                            this,
                            "Transpiled %[file]s (%s) to %[file]s (%s) (cache miss), version: %s, hash: %s, tail: %s, cache enabled: %b, cache dir: %[file]s",
                            source,
                            Transpiling.info(source),
                            target,
                            Transpiling.info(target),
                            this.version,
                            hsh.get(),
                            tail,
                            this.cacheEnabled,
                            cdir
                        );
                        return res;
                    }
                )
            );
        } else {
            rewrite.compareAndSet(false, true);
            new Saved(transform.apply(xmir).toString(), target).value();
        }
        return this.javaGenerated(
            rewrite.get(), target, hsh.get(), this.transpileTests && !tojo.discovered()
        );
    }

    /**
     * File info for logging.
     * @param info Path to file
     * @return Info string
     * @throws IOException If fails
     */
    private static String info(final Path info) throws IOException {
        final String res;
        if (Files.exists(info)) {
            res = Files.getLastModifiedTime(info).toString();
        } else {
            res = "Not exists yet";
        }
        return res;
    }

    /**
     * Generate java files and count them.
     * @param rewrite Rewrite .java files even if they exist
     * @param target Full target path to XMIR after transpilation optimizations
     * @param hsh Tojo hash
     * @param tests Whether to generate test sources for this tojo
     * @return Amount of generated .java files
     * @throws IOException If fails to save files
     * @checkstyle ParameterNumberCheck (5 lines)
     */
    private int javaGenerated(
        final boolean rewrite,
        final Path target,
        final String hsh,
        final boolean tests
    ) throws IOException {
        final AtomicInteger saved = new AtomicInteger(0);
        if (Files.exists(target)) {
            final Xnav object = new Xnav(target).element("object");
            final Collection<Xnav> classes = object.elements(Filter.withName("class"))
                .collect(Collectors.toList());
            final boolean atom = object.path("/object/o/o[@name='λ']").findAny().isPresent();
            for (final Xnav clazz : classes) {
                final String jname = clazz.attribute("java-name").text().get();
                if (!atom || jname.endsWith("Test")) {
                    final Path tgt = new Place(jname).make(
                        this.generatedDir, Transpiling.JAVA
                    );
                    final Footprint java = new FpJavaGenerated(
                        clazz, new FileGenerationReport(saved, tgt, target)
                    );
                    new JavaPlaced(
                        new FpIfReleased(
                            hsh,
                            new FpAppliedWithCache(
                                java,
                                this.cached(hsh, jname),
                                new RewritePolicy(rewrite, tgt),
                                this.cacheEnabled
                            ),
                            java
                        ),
                        tgt,
                        this.generatedDir
                    ).exec(clazz, tests);
                }
            }
            Logger.debug(
                this,
                "Generated %d Java files from %[file]s",
                saved.get(), target
            );
        }
        return saved.get();
    }

    /**
     * Cached path supplier for a generated Java file.
     * @param hsh Hash
     * @param jname Java class name
     * @return Supplier of cached path
     */
    private Supplier<Path> cached(final String hsh, final String jname) {
        return new CachePath(
            this.cacheDir.resolve(Transpiling.CACHE),
            this.version(),
            hsh,
            this.generatedDir.relativize(
                new Place(jname).make(
                    this.generatedDir, Transpiling.JAVA
                )
            )
        );
    }
}
