/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import com.github.lombrozo.xnav.Xnav;
import com.jcabi.log.Logger;
import com.jcabi.xml.XML;
import com.jcabi.xml.XMLDocument;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collection;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Function;
import java.util.function.Supplier;
import org.eolang.parser.OnDefault;
import org.eolang.parser.OnDetailed;

/**
 * Transpile.
 *
 * <p>This class transpiles XMIR files into Java source files.
 * The goal of this class is to automate the process of transforming EO
 * intermediate representations (XMIRs) into Java code, optimize the output,
 * and integrate the results into the Maven build lifecycle for further
 * processing.</p>
 *
 * <p>This is one of the final goals that transpiles XMIRs to Java files generated by
 * {@link MjAssemble}, {@link MjParse} or {@link MjPull} goals.
 * The resulting Java files are stored in the {@link #DIR} directory.
 * The intermediate optimized XMIRs are stored in the {@link #PRE} directory.</p>
 *
 * @since 0.1
 */
final class Transpiling implements Step {

    /**
     * The directory where to transpile to.
     */
    static final String DIR = "5-transpile";

    /**
     * The directory where to put pre-transpile files.
     */
    static final String PRE = "5-pre-transpile";

    /**
     * Cache directory for transpiled sources.
     */
    private static final String CACHE = "transpiled";

    /**
     * XMIR sources to transpile.
     */
    private final Collection<TjForeign> sources;

    /**
     * Target directory.
     */
    private final Path target;

    /**
     * Generated sources directory.
     */
    private final Path generated;

    /**
     * Base cache directory.
     */
    private final Path cache;

    /**
     * Whether caching is enabled.
     */
    private final boolean enabled;

    /**
     * Whether to transpile tests.
     */
    private final boolean tests;

    /**
     * The plugin version, for the log.
     */
    private final String version;

    /**
     * Directories with the Java sources a human wrote.
     */
    private final Collection<Path> roots;

    /**
     * The XSL train that does the transpiling.
     */
    private final Transpilation train;

    /**
     * Cache guard, see {@link ConcurrentCache} for why it is one per instance.
     */
    private final ConcurrentCache guard;

    /**
     * Constructor.
     * @param srcs XMIR sources to transpile
     * @param target Target directory
     * @param generated Generated sources directory
     * @param cache Base cache directory
     * @param enabled Whether caching is enabled
     * @param ver Plugin version string
     * @param tests Whether to transpile tests
     * @param java Directories with the Java sources a human wrote
     * @param train The XSL train that does the transpiling
     * @param guard Cache guard, one per instance
     */
    Transpiling(
        final Collection<TjForeign> srcs,
        final Path target,
        final Path generated,
        final Path cache,
        final boolean enabled,
        final String ver,
        final boolean tests,
        final Collection<Path> java,
        final Transpilation train,
        final ConcurrentCache guard
    ) {
        this.sources = srcs;
        this.target = target;
        this.generated = generated;
        this.cache = cache;
        this.enabled = enabled;
        this.tests = tests;
        this.version = ver;
        this.roots = java;
        this.train = train;
        this.guard = guard;
    }

    @Override
    public void exec() throws IOException {
        final JavaFiles files = new JavaFiles(
            this.generated,
            this.cache.resolve(Transpiling.CACHE).resolve(this.version()),
            this.enabled
        );
        final int transpiled = new Threaded<>(
            this.sources,
            tojo -> this.transpiled(tojo, files)
        ).total();
        files.removeStale();
        Logger.info(
            this, "Transpiled %d XMIRs, created %d Java files in %[file]s",
            this.sources.size(),
            transpiled + new PackageInfos(
                this.generated, this.roots, files.directories()
            ).create(),
            this.generated
        );
    }

    /**
     * The cache-key version segment of this transpiling.
     * @return The version segment for {@link CachePath}
     */
    String version() {
        return this.train.version();
    }

    private int transpiled(final TjForeign tojo, final JavaFiles files) throws IOException {
        final Path source = tojo.xmir();
        final XML xmir = new XMLDocument(source);
        final Path base = this.target.resolve(Transpiling.DIR);
        final String name = new OnDetailed(new OnDefault(new Xnav(xmir.inner())), source).get();
        final Path dest = new Place(name).make(base, MjAssemble.XMIR);
        final Supplier<String> hsh = new TojoHash(tojo);
        final AtomicBoolean rewrite = new AtomicBoolean(false);
        final Function<XML, XML> transform = this.train.forSource(name);
        final Path cdir = this.cache.resolve(Transpiling.CACHE);
        final Path tail = base.relativize(dest);
        if (this.enabled && !this.train.steps()) {
            this.guard.apply(
                source, dest, tail,
                new Cache(
                    new CachePath(cdir, this.version(), hsh.get()),
                    src -> {
                        rewrite.compareAndSet(false, true);
                        final String res = transform.apply(xmir).toString();
                        Logger.debug(
                            this,
                            "Transpiled %[file]s (%s) to %[file]s (%s) (cache miss), version: %s, hash: %s, tail: %s, cache enabled: %b, cache dir: %[file]s",
                            source,
                            Transpiling.info(source),
                            dest,
                            Transpiling.info(dest),
                            this.version,
                            hsh.get(),
                            tail,
                            this.enabled,
                            cdir
                        );
                        return res;
                    }
                )
            );
        } else {
            rewrite.compareAndSet(false, true);
            new Saved(transform.apply(xmir).toString(), dest).value();
        }
        return files.total(
            rewrite.get(), dest, hsh.get(), this.tests && !tojo.discovered()
        );
    }

    private static String info(final Path info) throws IOException {
        final String res;
        if (Files.exists(info)) {
            res = Files.getLastModifiedTime(info).toString();
        } else {
            res = "Not exists yet";
        }
        return res;
    }
}
