/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import com.jcabi.log.Logger;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Core unspiling logic: removes .class files compiled from autogenerated sources
 * so they are not included in the result JAR.
 *
 * @since 0.61.0
 */
final class Unspiling implements Step {

    /**
     * Pattern for matching paths ended with .java.
     */
    private static final Pattern JAVA = Pattern.compile("\\.java$");

    /**
     * Directory with generated Java sources.
     */
    private final Path generated;

    /**
     * Directory with compiled .class files.
     */
    private final Path classes;

    /**
     * Binaries to keep (GLOB filters).
     */
    private final Set<String> keep;

    /**
     * Constructor.
     *
     * @param generated Directory with generated Java sources
     * @param classes Directory with compiled .class files
     * @param keep Binaries to keep
     */
    Unspiling(
        final Path generated,
        final Path classes,
        final Set<String> keep
    ) {
        this.generated = generated;
        this.classes = classes;
        this.keep = keep;
    }

    @Override
    public void exec() throws IOException {
        final Walk walk = new WkDefault(this.classes);
        if (walk.isEmpty()) {
            Logger.warn(this, "No .class files in %[file]s, nothing to unspile", this.classes);
        } else {
            this.unspile(walk);
        }
    }

    private void unspile(final Walk walk) {
        final Collection<Path> filtered = new ArrayList<>(
            walk.excludes(this.keep).includes(
                new WkDefault(this.generated).stream()
                    .filter(path -> Unspiling.JAVA.matcher(path.toString()).find()).map(
                        path -> Unspiling.JAVA.matcher(
                            this.generated.relativize(path).toString()
                        ).replaceAll("").replace(File.separatorChar, '/')
                    ).flatMap(
                        name -> Stream.of(
                            String.format("%s.class", name),
                            String.format("%s$[1-9]*.class", name),
                            String.format("%s$EOΦ*.class", name)
                        )
                    ).collect(Collectors.toSet())
            )
        );
        if (filtered.isEmpty()) {
            Logger.info(
                this, "No .class files out of %d deleted in %[file]s",
                walk.size(), this.classes
            );
        } else {
            final int unspiled = new Threaded<>(
                filtered,
                path -> {
                    final int deleted;
                    if (Files.deleteIfExists(path)) {
                        Logger.debug(
                            this,
                            "Deleted %[file]s since was compiled from %[file]s",
                            path, this.generated
                        );
                        deleted = 1;
                    } else {
                        deleted = 0;
                    }
                    return deleted;
                }
            ).total();
            new EmptyDirectoriesIn(this.classes).clear();
            Logger.info(
                this,
                "Deleted %d .class files in %[file]s",
                unspiled, this.classes
            );
        }
    }
}
