/*
 * SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
 * SPDX-License-Identifier: MIT
 */
package org.eolang.maven;

import com.jcabi.log.Logger;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * Core unspiling logic: removes .class files compiled from autogenerated sources
 * so they are not included in the result JAR.
 * @since 0.61.0
 */
final class Unspiling implements Step {

    /**
     * Pattern for matching paths ended with .class.
     */
    private static final Pattern JAVA = Pattern.compile("\\.java$");

    /**
     * Inner auto generated classes.
     * <p>These globs are used for inner classes which may look like:
     * - EO_org/EO_eolang/EOnumber$1$2$4.class
     * - EO_org/EO_eolang/EO_sm/EOsocket$EOΦorgeolangsyssocketα0ρ.class</p>
     */
    private static final Collection<String> INNER = List.of(
        "**/EO*$[1-9]*.class", "**/*$EOΦ*.class"
    );

    /**
     * Directory with generated Java sources.
     */
    private final Path generated;

    /**
     * Directory with compiled .class files.
     */
    private final Path classes;

    /**
     * Binaries to keep (GLOB filters).
     */
    private final Set<String> keep;

    /**
     * Constructor.
     * @param generated Directory with generated Java sources
     * @param classes Directory with compiled .class files
     * @param keep Binaries to keep
     */
    Unspiling(
        final Path generated,
        final Path classes,
        final Set<String> keep
    ) {
        this.generated = generated;
        this.classes = classes;
        this.keep = keep;
    }

    @Override
    public void exec() throws IOException {
        final Walk walk = new Walk(this.classes);
        if (walk.isEmpty()) {
            Logger.warn(this, "No .class files in %[file]s, nothing to unspile", this.classes);
        } else {
            this.unspile(walk);
        }
    }

    /**
     * Unspile classes.
     * @param walk Collection of compiled classes
     */
    @SuppressWarnings("PMD.UnnecessaryLocalRule")
    private void unspile(final Walk walk) {
        final Set<String> included = new Walk(this.generated)
            .stream().map(
                path -> Unspiling.JAVA.matcher(
                    this.generated.relativize(path).toString()
                ).replaceAll(".class").replace(File.separatorChar, '/')
            )
            .collect(Collectors.toSet());
        included.addAll(Unspiling.INNER);
        final Collection<Path> filtered = new ArrayList<>(
            walk.excludes(this.keep).includes(included)
        );
        if (filtered.isEmpty()) {
            Logger.info(
                this, "No .class files out of %d deleted in %[file]s",
                walk.size(), this.classes
            );
        } else {
            final int unspiled = new Threaded<>(
                filtered,
                path -> {
                    final int deleted;
                    if (Files.deleteIfExists(path)) {
                        Logger.debug(
                            this,
                            "Deleted %[file]s since was compiled from %[file]s",
                            path, this.generated
                        );
                        deleted = 1;
                    } else {
                        deleted = 0;
                    }
                    return deleted;
                }
            ).total();
            new EmptyDirectoriesIn(this.classes).clear();
            Logger.info(
                this,
                "Deleted %d .class files in %[file]s",
                unspiled, this.classes
            );
        }
    }
}
