
/* This file was auto-generated by eo-maven-plugin (1.0-SNAPSHOT b5f50eb 2023-08-23T18:33:26) on 2023-08-24T11:58:23.295065Z; your changes will be discarded on the next build */
package EOorg.EOeolang;

import org.eolang.*;
import java.util.concurrent.atomic.AtomicBoolean;

// <o abstract="" ancestors="1" line="64" loc="Φ.org.eolang.int$gte" name="int$gte" original-name="gte" parent="int" pos="2"> 
//   <o line="65" loc="Φ.org.eolang.int$gte.x" name="x" pos="3"/>
//   <o base=".not" line="66" loc="Φ.org.eolang.int$gte.φ" name="@" pos="4"> 
//     <o base=".lt" line="67" loc="Φ.org.eolang.int$gte.φ.ρ" pos="7"> 
//       <o base="^" line="67" loc="Φ.org.eolang.int$gte.φ.ρ.ρ" pos="6"/>
//       <o base="x" line="67" loc="Φ.org.eolang.int$gte.φ.ρ.α0" pos="11" ref="65"/>
//     </o>
//   </o>
// </o>
@XmirObject(name = "int$gte", oname = "gte", source = "/home/tardis3/eo/eo-runtime/src/main/eo/org/eolang/int.eo")
public final class EOint$EOgte extends PhDefault {
    
  public EOint$EOgte(final Phi sigma) {
    super(sigma);
    this.add("x", new AtFree(/* default */));
    this.add("φ", new AtOnce(new AtComposite(this, rho -> {
      Phi ret_base_base = new PhMethod(rho, "ρ");
        ret_base_base = new PhLocated(ret_base_base, 67, 6, "Φ.org.eolang.int$gte.φ.ρ.ρ");
      Phi ret_base = new PhMethod(ret_base_base, "lt");
        ret_base = new PhLocated(ret_base, 67, 7, "Φ.org.eolang.int$gte.φ.ρ");
      ret_base = new PhCopy(ret_base);
        Phi ret_base_1 = new PhMethod(rho, "x");
          ret_base_1 = new PhLocated(ret_base_1, 67, 11, "Φ.org.eolang.int$gte.φ.ρ.α0");
        ret_base = new PhWith(ret_base, 0, ret_base_1);
      Phi ret = new PhMethod(ret_base, "not");
        ret = new PhLocated(ret, 66, 4, "Φ.org.eolang.int$gte.φ");
      return ret;
    })));
  }
}
