# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: jacoco
'on':
  pull_request:
    branches:
      - master
concurrency:
  group: jacoco-${{ github.ref }}
  cancel-in-progress: true
jobs:
  jacoco:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - uses: JesseTG/rm@v1.0.3
        with:
          path: ~/.m2/repository/org/eolang
      - run: mvn clean install -ntp -DskipITs -Pjacoco --errors --batch-mode
