# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: pdd
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: pdd-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pdd:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: volodya-lombrozo/pdd-action@69842b56627431c5f232f5ea2dc2fca82f409c54 # master
