# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: qulice
'on':
  pull_request:
    branches:
      - master
concurrency:
  group: qulice-${{ github.ref }}
  cancel-in-progress: true
jobs:
  qulice:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 26
      - uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ubuntu-qulice-jdk-26-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-qulice-jdk-26-maven-
      - run: mvn -ntp -Pqulice --errors --batch-mode -Deo.skip clean process-classes qulice:check
