# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
name: suppressions
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  THRESHOLD: 663
jobs:
  suppressions:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - run: |
          found=$(( $(git ls-files -z '*.java' \
            | xargs -0 grep -oh -e '@SuppressWarnings' -e '@checkstyle' \
            | wc -l) ))
          echo "Found ${found} suppressions, threshold is ${THRESHOLD}"
          if [ "${found}" -gt "${THRESHOLD}" ]; then
            echo "Too many suppressions in .java files: ${found} > ${THRESHOLD}"
            exit 1
          fi
