# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: telegram
'on':
  push:
    tags:
      - '*'
concurrency:
  group: telegram-${{ github.ref }}
  cancel-in-progress: true
jobs:
  telegram:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: djdefi/cloc-action@7
        with:
          options: --json --report-file=cloc.json
      - run: sudo apt-get update --yes --fix-missing && sudo apt-get install --yes jq bc
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.2
          bundler-cache: true
      - run: gem install hoc
      - run: .github/telegram.sh ${{ github.ref_name }}
      - uses: appleboy/telegram-action@master
        with:
          to: -1001381878846
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message_file: message.md
          disable_web_page_preview: true
          disable_notification: true
          format: markdown
