# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: trufflehog-oss
'on':
  push:
    branches:
      - master
permissions:
  contents: read
concurrency:
  group: trufflehog-oss-${{ github.ref }}
  cancel-in-progress: false
jobs:
  trufflehog:
    timeout-minutes: 25
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@48b58d3bf3f02ba17bf23b87f095499bc80c6fd7 # main
        with:
          extra_args: --only-verified
