# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: xslint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: xslint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  xslint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: xslint/xslint-action@0.0.9
        with:
          config: .xslint.yml
